//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotePalaceWebApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomCategory
    {
        public RoomCategory()
        {
            this.Rooms = new HashSet<Rooms>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public float PricePerNight { get; set; }
    
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
