//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotePalaceWebApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Reserves = new HashSet<Reserves>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Floor { get; set; }
        public int Beds { get; set; }
        public int CategoryID { get; set; }
    
        public virtual ICollection<Reserves> Reserves { get; set; }
        public virtual RoomCategory RoomCategory { get; set; }
    }
}
